### PR TITLE
Use failures for exit code

### PR DESCRIPTION
**Pull request by c0d3d**
This is a fix for #98 & #93

### CODE REVIEW

**Comment by c0d3d** [comment]
@michaelmoussa Do you mind taking a look at this?

**Comment by Thana404** [comment]
If it can be of any use for a merge consideration, I encountered the same issue as #98 and #93 (an error always result as exit code 0) and this PR just fixed it.

**Comment by c0d3d** [comment]
@Thana404 Now if we could only get this merged :P

This repo seems pretty dead.

**Comment by mpuittinen** [comment]
Merged and included in package 1.10.0

**Pull request merged**
